name: chlamy-mutant-motility
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - natsort=8.4.0
  - click=8.1.7
  - scikit-image=0.22.0
  - python=3.12
  - jupyterlab=4.1.8
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.8.4
  - tqdm=4.66.2
  - seaborn=0.13.2
  - pip:
    - ipympl==0.9.4
    - arcadia-pycolor==0.5.0
    - ipywidgets==8.1.2
